### PR TITLE
Add support for custom middleware

### PR DESCRIPTION
**Pull request by fadeenk**

### CODE REVIEW

**Comment by lpinca** [comment]
LGTM, maybe we should put all options under a namespace to prevent collisions with other plugins but that is a separate issue.

**Comment by lpinca** [comment]
@fadeenk I pushed a commit to your branch to fix some nits, let me know if you are ok with it.

**Comment by fadeenk** [comment]
It looks great to me :) And I agree it was a bit weird having the options like that, but like you mentioned that's a separate issue

**Comment by lpinca** [comment]
Will cut 2.1.0 later today or tomorrow.

**Comment by lpinca** [comment]
Thanks!

**Pull request merged**
